# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml
name: get-identity
channels:
  - bioconda
  - defaults
dependencies:
  - pysam
  - kraken-biom
  - python=3.6
